### ISSUE TITLE
Add ability to take an average of color samples to find most prevalent/dominant poster color

### ISSUE THREAD

**Issue by danlwright** [philosowaffle/plex-lifx-webhook#3]

**Comment by philosowaffle** [comment]
I think you can configure this already by setting `NumColors=1` in the config.ini.

According to the ColorThief [documentation](https://github.com/fengsp/color-thief-py#usage), you can get the dominant color by calling `color_thief.get_color(quality=1)`.  However, if we [peek under the hood](https://github.com/fengsp/color-thief-py/blob/18a099ba3d9f649406ab1cfa75990df1cf658f03/colorthief.py#L50) we see that `get_color` is simply calling the same `color_palette` we are using and just picking the first color returned.  It appears that the first color returned from the color palette is considered the dominant color. 

Also, I have recently converted this script to be compatible with [Tatulli](http://tautulli.com/), you can find that version over [here](https://github.com/blacktwin/JBOPS/blob/master/fun/plex_lifx_color_theme.pyw).

**Comment by danlwright** [comment]
Thanks for the reply. I do use Tautulli, so I will check out the new version.
