### ISSUE TITLE
Issue with configuration

### ISSUE THREAD

**Issue by lsvMoretti** [philosowaffle/plex-lifx-webhook#5]
Hello, I'm not sure if this is still up to date or relevant, however I am getting the following issue.

> Traceback (most recent call last):
  File "plexlifx.py", line 126, in <module>
    default_pause_uuid = scenes[default_pause_theme]
KeyError: 'Warm'

I've tried different themes in the app and that I have found on the web but no success.

**Comment by philosowaffle** [comment]
This indicates that the theme `Warm` was not found when the script queried the lifx api.  This needs to be a theme you have created and saved in your app.
